#!/bin/sh
echo "##### Installations begins ######"

pip install pandas
pip install PyYaml
pip install shapely
pip install geopandas
pip install numpy
pip install matplotlib
pip install folium
pip install geopy

